// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class ButacasReservada
{
    public int IdButacaRes { get; set; }

    public int? IdReserva { get; set; }

    public int? Butaca { get; set; }

    public int? IdEstadoButRes { get; set; }

    public virtual EstadoButacasReservada IdEstadoButResNavigation { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }
}