// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Calle
{
    public int IdCalle { get; set; }

    public string Calle1 { get; set; }

    public virtual ICollection<Direccione> Direcciones { get; set; } = new List<Direccione>();
}