// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public DateTime FechaRegistro { get; set; }

    public int? IdDireccion { get; set; }

    public int? PuntosFidelidad { get; set; }

    public string NombreCliente { get; set; }

    public string ApellidoCliente { get; set; }

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}