// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class CombosKiosco
{
    public int CodCombo { get; set; }

    public int? CodPrecioCombo { get; set; }

    public int? Cantidad { get; set; }

    public virtual PreciosCombo CodPrecioComboNavigation { get; set; }

    public virtual ICollection<DetalleCombo> DetalleCombos { get; set; } = new List<DetalleCombo>();
}