// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Comprobante
{
    public int CodComprobante { get; set; }

    public int? IdCliente { get; set; }

    public int? IdEmpleado { get; set; }

    public int? IdFcompra { get; set; }

    public int? IdFpago { get; set; }

    public bool? ConfirmPago { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<DetalleKiosco> DetalleKioscos { get; set; } = new List<DetalleKiosco>();

    public virtual ICollection<DetalleTicket> DetalleTickets { get; set; } = new List<DetalleTicket>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual FormasCompra IdFcompraNavigation { get; set; }

    public virtual FormasPago IdFpagoNavigation { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}