// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DescuentoCliente
{
    public int IdDesCliente { get; set; }

    public decimal? Descuento { get; set; }

    public virtual ICollection<TiposCliente> TiposClientes { get; set; } = new List<TiposCliente>();
}