// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DetalleKiosco
{
    public int CodDetalleKiosco { get; set; }

    public int? CodComprobante { get; set; }

    public int? CodKiosco { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? PreUnitario { get; set; }

    public virtual Comprobante CodComprobanteNavigation { get; set; }

    public virtual ProductosKiosco CodKioscoNavigation { get; set; }
}