// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DetalleCombo
{
    public int CodDetCombo { get; set; }

    public int? CodCombo { get; set; }

    public int? CodProdKiosco { get; set; }

    public virtual CombosKiosco CodComboNavigation { get; set; }

    public virtual ProductosKiosco CodProdKioscoNavigation { get; set; }
}