// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DetallesIdioma
{
    public int IdDetIdioma { get; set; }

    public int? IdIdioma { get; set; }

    public int? CodPelicula { get; set; }

    public virtual Pelicula CodPeliculaNavigation { get; set; }

    public virtual Idioma IdIdiomaNavigation { get; set; }
}