// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DetallesSala
{
    public int IdDetSala { get; set; }

    public int? IdPrecioSala { get; set; }

    public int? IdCantButacas { get; set; }

    public virtual CantidadButaca IdCantButacasNavigation { get; set; }

    public virtual PreciosSala IdPrecioSalaNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}