// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class DetalleTicket
{
    public int CodDetalleTicket { get; set; }

    public int? CodComprobante { get; set; }

    public int? CodTicket { get; set; }

    public int? CantidadTicket { get; set; }

    public decimal? Subtotal { get; set; }

    public virtual Comprobante CodComprobanteNavigation { get; set; }

    public virtual Ticket CodTicketNavigation { get; set; }
}