// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Direccione
{
    public int IdDireccion { get; set; }

    public int? IdBarrio { get; set; }

    public int? IdCalle { get; set; }

    public int? Altura { get; set; }

    public int? Piso { get; set; }

    public string Letra { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Calle IdCalleNavigation { get; set; }
}