// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public int? Legajo { get; set; }

    public int? IdPuesto { get; set; }

    public int? IdRol { get; set; }

    public decimal? Salario { get; set; }

    public int? IdDireccion { get; set; }

    public string NombreEmpleado { get; set; }

    public string ApellidoEmpleado { get; set; }

    public string NroTelefono { get; set; }

    public string Email { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public int? IdSexo { get; set; }

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();

    public virtual Direccione IdDireccionNavigation { get; set; }

    public virtual Puesto IdPuestoNavigation { get; set; }

    public virtual Role IdRolNavigation { get; set; }

    public virtual Sexo IdSexoNavigation { get; set; }
}