// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class EstadoSala
{
    public int CodEstado { get; set; }

    public int? IdSalas { get; set; }

    public virtual Sala IdSalasNavigation { get; set; }
}