// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class EstadoButacasReservada
{
    public int IdEstadoButRes { get; set; }

    public string EstadoButRes { get; set; }

    public virtual ICollection<ButacasReservada> ButacasReservada { get; set; } = new List<ButacasReservada>();
}