// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class EstadoReserva
{
    public int IdEstadoReserva { get; set; }

    public string EstadoReserva1 { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}