// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Fecha
{
    public int IdFecha { get; set; }

    public DateTime? Fecha1 { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<PromosFecha> PromosFechas { get; set; } = new List<PromosFecha>();

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}