// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Formato
{
    public int IdFormato { get; set; }

    public string Formato1 { get; set; }

    public virtual ICollection<Pelicula> Peliculas { get; set; } = new List<Pelicula>();
}