// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Funcione
{
    public int CodFuncion { get; set; }

    public int? IdSala { get; set; }

    public int? CodPelicula { get; set; }

    public int? IdFecha { get; set; }

    public int? IdHorario { get; set; }

    public int? IdButacaRes { get; set; }

    public virtual Pelicula CodPeliculaNavigation { get; set; }

    public virtual Fecha IdFechaNavigation { get; set; }

    public virtual Horario IdHorarioNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}