// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class GenerosPelicula
{
    public int IdGenero { get; set; }

    public string Genero { get; set; }

    public virtual ICollection<DetallesGenero> DetallesGeneros { get; set; } = new List<DetallesGenero>();
}