// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Horario
{
    public int IdHorario { get; set; }

    public TimeOnly? HoraInicio { get; set; }

    public TimeOnly? HoraFin { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<PromosHorario> PromosHorarios { get; set; } = new List<PromosHorario>();

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();
}