// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Idioma1 { get; set; }

    public virtual ICollection<DetallesIdioma> DetallesIdiomas { get; set; } = new List<DetallesIdioma>();
}