// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TP_BD_P3.Models.Scaffolded;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial interface ITP_BD_P2ContextProcedures
    {
        Task<List<sp_ReporteConsumoKioscoResult>> sp_ReporteConsumoKioscoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_TopGeneroPorTipoClienteResult>> sp_TopGeneroPorTipoClienteAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_RecaudacionPorPeliculaResult>> usp_RecaudacionPorPeliculaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_TopProductosKioscoPorGenero_AnioActualResult>> usp_TopProductosKioscoPorGenero_AnioActualAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
