// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Pelicula
{
    public int CodPelicula { get; set; }

    public string Titulo { get; set; }

    public int? IdFormato { get; set; }

    public int? DuracionMin { get; set; }

    public int? IdPais { get; set; }

    public int? IdClasif { get; set; }

    public virtual ICollection<DetalleSubtitulo> DetalleSubtitulos { get; set; } = new List<DetalleSubtitulo>();

    public virtual ICollection<DetallesGenero> DetallesGeneros { get; set; } = new List<DetallesGenero>();

    public virtual ICollection<DetallesIdioma> DetallesIdiomas { get; set; } = new List<DetallesIdioma>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual Clasificacione IdClasifNavigation { get; set; }

    public virtual Formato IdFormatoNavigation { get; set; }

    public virtual Paise IdPaisNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}