// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class PreciosCombo
{
    public int CodPrecioCombo { get; set; }

    public decimal? PrecioCombo { get; set; }

    public virtual ICollection<CombosKiosco> CombosKioscos { get; set; } = new List<CombosKiosco>();
}