// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class PreciosProducto
{
    public int CodPrecioProd { get; set; }

    public decimal? Precio { get; set; }

    public int? CodProdKiosco { get; set; }

    public virtual ProductosKiosco CodProdKioscoNavigation { get; set; }
}