// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class PreciosSala
{
    public int IdPreciosSala { get; set; }

    public decimal? PrecioSala { get; set; }

    public virtual ICollection<DetallesSala> DetallesSalas { get; set; } = new List<DetallesSala>();
}