// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class ProductosKiosco
{
    public int CodProdKiosco { get; set; }

    public string Producto { get; set; }

    public virtual ICollection<DetalleCombo> DetalleCombos { get; set; } = new List<DetalleCombo>();

    public virtual ICollection<DetalleKiosco> DetalleKioscos { get; set; } = new List<DetalleKiosco>();

    public virtual ICollection<PreciosProducto> PreciosProductos { get; set; } = new List<PreciosProducto>();
}