// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class PromosHorario
{
    public int CodPromoHorario { get; set; }

    public int? IdPromo { get; set; }

    public int? IdHorario { get; set; }

    public virtual Horario IdHorarioNavigation { get; set; }

    public virtual Promocione IdPromoNavigation { get; set; }
}