// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class PromosFecha
{
    public int CodPromoFecha { get; set; }

    public int? IdPromo { get; set; }

    public int? IdFecha { get; set; }

    public virtual Fecha IdFechaNavigation { get; set; }

    public virtual Promocione IdPromoNavigation { get; set; }
}