// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Promocione
{
    public int IdPromo { get; set; }

    public string Promocion { get; set; }

    public decimal? Descuento { get; set; }

    public virtual ICollection<PromosFecha> PromosFechas { get; set; } = new List<PromosFecha>();

    public virtual ICollection<PromosHorario> PromosHorarios { get; set; } = new List<PromosHorario>();
}