// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int? IdCliente { get; set; }

    public int? CodComprobante { get; set; }

    public int? CodFuncion { get; set; }

    public DateTime FechaReserva { get; set; }

    public DateTime FechaVenc { get; set; }

    public int? IdEstadoReserva { get; set; }

    public virtual ICollection<ButacasReservada> ButacasReservada { get; set; } = new List<ButacasReservada>();

    public virtual Comprobante CodComprobanteNavigation { get; set; }

    public virtual Funcione CodFuncionNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadoReserva IdEstadoReservaNavigation { get; set; }
}