// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Sala
{
    public int IdSala { get; set; }

    public int? CodPelicula { get; set; }

    public int? IdDetSala { get; set; }

    public int? IdHorario { get; set; }

    public int? IdFecha { get; set; }

    public virtual Pelicula CodPeliculaNavigation { get; set; }

    public virtual ICollection<EstadoSala> EstadoSalas { get; set; } = new List<EstadoSala>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual DetallesSala IdDetSalaNavigation { get; set; }

    public virtual Fecha IdFechaNavigation { get; set; }

    public virtual Horario IdHorarioNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}