// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial class sp_ReporteConsumoKioscoResult
    {
        public int? categorias_analizadas { get; set; }
        public int? total_productos_top3 { get; set; }
        public int? total_combos_top3 { get; set; }
        [Column("ganancia_total_top6", TypeName = "decimal(38,2)")]
        public decimal? ganancia_total_top6 { get; set; }
    }
}
