// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial class sp_TopGeneroPorTipoClienteResult
    {
        [Column("Tipo de cliente")]
        [StringLength(255)]
        public string Tipodecliente { get; set; }
        [StringLength(255)]
        public string Género { get; set; }
        [Column("Cantidad de peliculas en el año")]
        public int? Cantidaddepeliculasenelaño { get; set; }
        [Column("Cantidad de ventas")]
        public int? Cantidaddeventas { get; set; }
        [Column("Monto total de ventas", TypeName = "decimal(38,2)")]
        public decimal? Montototaldeventas { get; set; }
        [Column("Promedio de asistencia por pelicula")]
        public double? Promediodeasistenciaporpelicula { get; set; }
    }
}
