// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Subtitulo
{
    public int IdSubtitulo { get; set; }

    public string IdiomaSubt { get; set; }

    public virtual ICollection<DetalleSubtitulo> DetalleSubtitulos { get; set; } = new List<DetalleSubtitulo>();
}