// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class Ticket
{
    public int CodTicket { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdSala { get; set; }

    public int? CodPelicula { get; set; }

    public int? NroButaca { get; set; }

    public DateTime? FechaFuncion { get; set; }

    public TimeOnly? HorarioFuncion { get; set; }

    public int? IdTCliente { get; set; }

    public virtual Pelicula CodPeliculaNavigation { get; set; }

    public virtual ICollection<DetalleTicket> DetalleTickets { get; set; } = new List<DetalleTicket>();

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual TiposCliente IdTClienteNavigation { get; set; }
}