// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class TiposCliente
{
    public int IdTCliente { get; set; }

    public string TCliente { get; set; }

    public int? IdDesCliente { get; set; }

    public virtual DescuentoCliente IdDesClienteNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}