// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TP_BD_P3.Models.Scaffolded;

public partial class TP_BD_P2Context : DbContext
{
    public TP_BD_P2Context(DbContextOptions<TP_BD_P2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Barrio> Barrios { get; set; }

    public virtual DbSet<ButacasReservada> ButacasReservadas { get; set; }

    public virtual DbSet<Calle> Calles { get; set; }

    public virtual DbSet<CantidadButaca> CantidadButacas { get; set; }

    public virtual DbSet<Clasificacione> Clasificaciones { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<CombosKiosco> CombosKioscos { get; set; }

    public virtual DbSet<Comprobante> Comprobantes { get; set; }

    public virtual DbSet<DescuentoCliente> DescuentoClientes { get; set; }

    public virtual DbSet<DetalleCombo> DetalleCombos { get; set; }

    public virtual DbSet<DetalleKiosco> DetalleKioscos { get; set; }

    public virtual DbSet<DetalleSubtitulo> DetalleSubtitulos { get; set; }

    public virtual DbSet<DetalleTicket> DetalleTickets { get; set; }

    public virtual DbSet<DetallesGenero> DetallesGeneros { get; set; }

    public virtual DbSet<DetallesIdioma> DetallesIdiomas { get; set; }

    public virtual DbSet<DetallesSala> DetallesSalas { get; set; }

    public virtual DbSet<Direccione> Direcciones { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<EstadoButacasReservada> EstadoButacasReservadas { get; set; }

    public virtual DbSet<EstadoReserva> EstadoReservas { get; set; }

    public virtual DbSet<EstadoSala> EstadoSalas { get; set; }

    public virtual DbSet<Fecha> Fechas { get; set; }

    public virtual DbSet<FormasCompra> FormasCompras { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    public virtual DbSet<Formato> Formatos { get; set; }

    public virtual DbSet<Funcione> Funciones { get; set; }

    public virtual DbSet<GenerosPelicula> GenerosPeliculas { get; set; }

    public virtual DbSet<Horario> Horarios { get; set; }

    public virtual DbSet<Idioma> Idiomas { get; set; }

    public virtual DbSet<Paise> Paises { get; set; }

    public virtual DbSet<Pelicula> Peliculas { get; set; }

    public virtual DbSet<PreciosCombo> PreciosCombos { get; set; }

    public virtual DbSet<PreciosProducto> PreciosProductos { get; set; }

    public virtual DbSet<PreciosSala> PreciosSalas { get; set; }

    public virtual DbSet<ProductosKiosco> ProductosKioscos { get; set; }

    public virtual DbSet<Promocione> Promociones { get; set; }

    public virtual DbSet<PromosFecha> PromosFechas { get; set; }

    public virtual DbSet<PromosHorario> PromosHorarios { get; set; }

    public virtual DbSet<Puesto> Puestos { get; set; }

    public virtual DbSet<Reserva> Reservas { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Sala> Salas { get; set; }

    public virtual DbSet<Sexo> Sexos { get; set; }

    public virtual DbSet<Subtitulo> Subtitulos { get; set; }

    public virtual DbSet<Ticket> Tickets { get; set; }

    public virtual DbSet<TiposCliente> TiposClientes { get; set; }

    public virtual DbSet<VistaRecaudacion> VistaRecaudacions { get; set; }

    public virtual DbSet<VwGastoPorGeneroDuracion> VwGastoPorGeneroDuracions { get; set; }

    public virtual DbSet<VwTopCombo> VwTopCombos { get; set; }

    public virtual DbSet<VwTopProductosIndividuale> VwTopProductosIndividuales { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barrio>(entity =>
        {
            entity.HasKey(e => e.IdBarrio).HasName("PK__barrios__1121F0B2B710F5F2");

            entity.ToTable("barrios");

            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.Barrio1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("barrio");
        });

        modelBuilder.Entity<ButacasReservada>(entity =>
        {
            entity.HasKey(e => e.IdButacaRes).HasName("PK__butacas___1597620580A66CF4");

            entity.ToTable("butacas_reservadas");

            entity.Property(e => e.IdButacaRes).HasColumnName("id_butaca_res");
            entity.Property(e => e.Butaca).HasColumnName("butaca");
            entity.Property(e => e.IdEstadoButRes).HasColumnName("id_estado_but_res");
            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");

            entity.HasOne(d => d.IdEstadoButResNavigation).WithMany(p => p.ButacasReservada)
                .HasForeignKey(d => d.IdEstadoButRes)
                .HasConstraintName("fk_butacasreservadas_estado");

            entity.HasOne(d => d.IdReservaNavigation).WithMany(p => p.ButacasReservada)
                .HasForeignKey(d => d.IdReserva)
                .HasConstraintName("fk_butacasreservadas_reserva");
        });

        modelBuilder.Entity<Calle>(entity =>
        {
            entity.HasKey(e => e.IdCalle).HasName("PK__calles__C031D088FD321D4D");

            entity.ToTable("calles");

            entity.Property(e => e.IdCalle).HasColumnName("id_calle");
            entity.Property(e => e.Calle1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("calle");
        });

        modelBuilder.Entity<CantidadButaca>(entity =>
        {
            entity.HasKey(e => e.IdCantButacas).HasName("PK__cantidad__7F67B2359B50320E");

            entity.ToTable("cantidad_butacas");

            entity.Property(e => e.IdCantButacas).HasColumnName("id_cant_butacas");
            entity.Property(e => e.CantButacas).HasColumnName("cant_butacas");
        });

        modelBuilder.Entity<Clasificacione>(entity =>
        {
            entity.HasKey(e => e.IdClasificacion).HasName("PK__clasific__257A4E1B40D01347");

            entity.ToTable("clasificaciones");

            entity.Property(e => e.IdClasificacion).HasColumnName("id_clasificacion");
            entity.Property(e => e.Clasificacion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("clasificacion");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__clientes__677F38F5ED68B9A9");

            entity.ToTable("clientes");

            entity.HasIndex(e => new { e.NombreCliente, e.ApellidoCliente }, "idx_clientes_nombre");

            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.ApellidoCliente)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("apellido_cliente");
            entity.Property(e => e.FechaRegistro)
                .HasColumnType("datetime")
                .HasColumnName("fecha_registro");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.NombreCliente)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("nombre_cliente");
            entity.Property(e => e.PuntosFidelidad).HasColumnName("puntos_fidelidad");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("fk_clientes_direccion");
        });

        modelBuilder.Entity<CombosKiosco>(entity =>
        {
            entity.HasKey(e => e.CodCombo).HasName("PK__combos_k__EB5E413F7FB8D9D5");

            entity.ToTable("combos_kiosco");

            entity.Property(e => e.CodCombo).HasColumnName("cod_combo");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodPrecioCombo).HasColumnName("cod_precio_combo");

            entity.HasOne(d => d.CodPrecioComboNavigation).WithMany(p => p.CombosKioscos)
                .HasForeignKey(d => d.CodPrecioCombo)
                .HasConstraintName("fk_combos_preciocombo");
        });

        modelBuilder.Entity<Comprobante>(entity =>
        {
            entity.HasKey(e => e.CodComprobante).HasName("PK__comproba__DF158E3291F90ACC");

            entity.ToTable("comprobante");

            entity.Property(e => e.CodComprobante).HasColumnName("cod_comprobante");
            entity.Property(e => e.ConfirmPago).HasColumnName("confirm_pago");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdEmpleado).HasColumnName("id_empleado");
            entity.Property(e => e.IdFcompra).HasColumnName("id_fcompra");
            entity.Property(e => e.IdFpago).HasColumnName("id_fpago");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("fk_comprobante_cliente");

            entity.HasOne(d => d.IdEmpleadoNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.IdEmpleado)
                .HasConstraintName("fk_comprobante_empleado");

            entity.HasOne(d => d.IdFcompraNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.IdFcompra)
                .HasConstraintName("fk_comprobante_forma_compra");

            entity.HasOne(d => d.IdFpagoNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.IdFpago)
                .HasConstraintName("fk_comprobante_forma_pago");
        });

        modelBuilder.Entity<DescuentoCliente>(entity =>
        {
            entity.HasKey(e => e.IdDesCliente).HasName("PK__descuent__5D67EC42A3FC5FB6");

            entity.ToTable("descuento_clientes");

            entity.Property(e => e.IdDesCliente).HasColumnName("id_des_cliente");
            entity.Property(e => e.Descuento)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("descuento");
        });

        modelBuilder.Entity<DetalleCombo>(entity =>
        {
            entity.HasKey(e => e.CodDetCombo).HasName("PK__detalle___41AAD9BD6F40612D");

            entity.ToTable("detalle_combos");

            entity.Property(e => e.CodDetCombo).HasColumnName("cod_det_combo");
            entity.Property(e => e.CodCombo).HasColumnName("cod_combo");
            entity.Property(e => e.CodProdKiosco).HasColumnName("cod_prod_kiosco");

            entity.HasOne(d => d.CodComboNavigation).WithMany(p => p.DetalleCombos)
                .HasForeignKey(d => d.CodCombo)
                .HasConstraintName("fk_detcombos_combo");

            entity.HasOne(d => d.CodProdKioscoNavigation).WithMany(p => p.DetalleCombos)
                .HasForeignKey(d => d.CodProdKiosco)
                .HasConstraintName("fk_detcombos_prod");
        });

        modelBuilder.Entity<DetalleKiosco>(entity =>
        {
            entity.HasKey(e => e.CodDetalleKiosco).HasName("PK__detalle___5BB2869FF3AC88B0");

            entity.ToTable("detalle_kiosco");

            entity.Property(e => e.CodDetalleKiosco).HasColumnName("cod_detalle_kiosco");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodComprobante).HasColumnName("cod_comprobante");
            entity.Property(e => e.CodKiosco).HasColumnName("cod_kiosco");
            entity.Property(e => e.PreUnitario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("pre_unitario");
            entity.Property(e => e.Subtotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("subtotal");

            entity.HasOne(d => d.CodComprobanteNavigation).WithMany(p => p.DetalleKioscos)
                .HasForeignKey(d => d.CodComprobante)
                .HasConstraintName("fk_detkiosco_comprobante");

            entity.HasOne(d => d.CodKioscoNavigation).WithMany(p => p.DetalleKioscos)
                .HasForeignKey(d => d.CodKiosco)
                .HasConstraintName("fk_detkiosco_prod");
        });

        modelBuilder.Entity<DetalleSubtitulo>(entity =>
        {
            entity.HasKey(e => e.IdDetSub).HasName("PK__detalle___3CD53E2F1C8D5C42");

            entity.ToTable("detalle_subtitulos");

            entity.Property(e => e.IdDetSub).HasColumnName("id_det_sub");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.IdSubtitulo).HasColumnName("id_subtitulo");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.DetalleSubtitulos)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_detsub_pelicula");

            entity.HasOne(d => d.IdSubtituloNavigation).WithMany(p => p.DetalleSubtitulos)
                .HasForeignKey(d => d.IdSubtitulo)
                .HasConstraintName("fk_detsub_subtitulo");
        });

        modelBuilder.Entity<DetalleTicket>(entity =>
        {
            entity.HasKey(e => e.CodDetalleTicket).HasName("PK__detalle___8C23D460784D0513");

            entity.ToTable("detalle_tickets");

            entity.Property(e => e.CodDetalleTicket).HasColumnName("cod_detalle_ticket");
            entity.Property(e => e.CantidadTicket).HasColumnName("cantidad_ticket");
            entity.Property(e => e.CodComprobante).HasColumnName("cod_comprobante");
            entity.Property(e => e.CodTicket).HasColumnName("cod_ticket");
            entity.Property(e => e.Subtotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("subtotal");

            entity.HasOne(d => d.CodComprobanteNavigation).WithMany(p => p.DetalleTickets)
                .HasForeignKey(d => d.CodComprobante)
                .HasConstraintName("fk_detalletickets_comprobante");

            entity.HasOne(d => d.CodTicketNavigation).WithMany(p => p.DetalleTickets)
                .HasForeignKey(d => d.CodTicket)
                .HasConstraintName("fk_detalletickets_ticket");
        });

        modelBuilder.Entity<DetallesGenero>(entity =>
        {
            entity.HasKey(e => e.IdDetalleGenero).HasName("PK__detalles__6756E255411C83F9");

            entity.ToTable("detalles_generos");

            entity.Property(e => e.IdDetalleGenero).HasColumnName("id_detalle_genero");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.IdGenero).HasColumnName("id_genero");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.DetallesGeneros)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_detgen_pelicula");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.DetallesGeneros)
                .HasForeignKey(d => d.IdGenero)
                .HasConstraintName("fk_detgen_genero");
        });

        modelBuilder.Entity<DetallesIdioma>(entity =>
        {
            entity.HasKey(e => e.IdDetIdioma).HasName("PK__detalles__8B9D18560F01F19E");

            entity.ToTable("detalles_idiomas");

            entity.Property(e => e.IdDetIdioma).HasColumnName("id_det_idioma");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.DetallesIdiomas)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_detidi_pelicula");

            entity.HasOne(d => d.IdIdiomaNavigation).WithMany(p => p.DetallesIdiomas)
                .HasForeignKey(d => d.IdIdioma)
                .HasConstraintName("fk_detidi_idioma");
        });

        modelBuilder.Entity<DetallesSala>(entity =>
        {
            entity.HasKey(e => e.IdDetSala).HasName("PK__detalles__503F73BAAAFA0CDE");

            entity.ToTable("detalles_salas");

            entity.Property(e => e.IdDetSala).HasColumnName("id_det_sala");
            entity.Property(e => e.IdCantButacas).HasColumnName("id_cant_butacas");
            entity.Property(e => e.IdPrecioSala).HasColumnName("id_precio_sala");

            entity.HasOne(d => d.IdCantButacasNavigation).WithMany(p => p.DetallesSalas)
                .HasForeignKey(d => d.IdCantButacas)
                .HasConstraintName("fk_detalles_salas_cant");

            entity.HasOne(d => d.IdPrecioSalaNavigation).WithMany(p => p.DetallesSalas)
                .HasForeignKey(d => d.IdPrecioSala)
                .HasConstraintName("fk_detalles_salas_precio");
        });

        modelBuilder.Entity<Direccione>(entity =>
        {
            entity.HasKey(e => e.IdDireccion).HasName("PK__direccio__25C35D07E6FD6DCB");

            entity.ToTable("direcciones");

            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.Altura).HasColumnName("altura");
            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.IdCalle).HasColumnName("id_calle");
            entity.Property(e => e.Letra)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("letra");
            entity.Property(e => e.Piso).HasColumnName("piso");

            entity.HasOne(d => d.IdBarrioNavigation).WithMany(p => p.Direcciones)
                .HasForeignKey(d => d.IdBarrio)
                .HasConstraintName("fk_direcciones_barrio");

            entity.HasOne(d => d.IdCalleNavigation).WithMany(p => p.Direcciones)
                .HasForeignKey(d => d.IdCalle)
                .HasConstraintName("fk_direcciones_calle");
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK__empleado__88B51394B2174A92");

            entity.ToTable("empleados");

            entity.HasIndex(e => e.Email, "idx_empleados_email");

            entity.Property(e => e.IdEmpleado).HasColumnName("id_empleado");
            entity.Property(e => e.ApellidoEmpleado)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("apellido_empleado");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FechaNacimiento)
                .HasColumnType("datetime")
                .HasColumnName("fecha_nacimiento");
            entity.Property(e => e.IdDireccion).HasColumnName("id_direccion");
            entity.Property(e => e.IdPuesto).HasColumnName("id_puesto");
            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.IdSexo).HasColumnName("id_sexo");
            entity.Property(e => e.Legajo).HasColumnName("legajo");
            entity.Property(e => e.NombreEmpleado)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("nombre_empleado");
            entity.Property(e => e.NroTelefono)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nro_telefono");
            entity.Property(e => e.Salario)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("salario");

            entity.HasOne(d => d.IdDireccionNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdDireccion)
                .HasConstraintName("fk_empleados_direccion");

            entity.HasOne(d => d.IdPuestoNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdPuesto)
                .HasConstraintName("fk_empleados_puesto");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdRol)
                .HasConstraintName("fk_empleados_rol");

            entity.HasOne(d => d.IdSexoNavigation).WithMany(p => p.Empleados)
                .HasForeignKey(d => d.IdSexo)
                .HasConstraintName("fk_empleados_sexo");
        });

        modelBuilder.Entity<EstadoButacasReservada>(entity =>
        {
            entity.HasKey(e => e.IdEstadoButRes).HasName("PK__estado_b__109548E7096954C5");

            entity.ToTable("estado_butacas_reservadas");

            entity.Property(e => e.IdEstadoButRes).HasColumnName("id_estado_but_res");
            entity.Property(e => e.EstadoButRes)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("estado_but_res");
        });

        modelBuilder.Entity<EstadoReserva>(entity =>
        {
            entity.HasKey(e => e.IdEstadoReserva).HasName("PK__estado_r__D1D0D7E08DE8DA8B");

            entity.ToTable("estado_reservas");

            entity.Property(e => e.IdEstadoReserva).HasColumnName("id_estado_reserva");
            entity.Property(e => e.EstadoReserva1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("estado_reserva");
        });

        modelBuilder.Entity<EstadoSala>(entity =>
        {
            entity.HasKey(e => e.CodEstado).HasName("PK__estado_s__D37A6AC5AFEB59D7");

            entity.ToTable("estado_salas");

            entity.Property(e => e.CodEstado).HasColumnName("cod_estado");
            entity.Property(e => e.IdSalas).HasColumnName("id_salas");

            entity.HasOne(d => d.IdSalasNavigation).WithMany(p => p.EstadoSalas)
                .HasForeignKey(d => d.IdSalas)
                .HasConstraintName("fk_estado_salas_sala");
        });

        modelBuilder.Entity<Fecha>(entity =>
        {
            entity.HasKey(e => e.IdFecha).HasName("PK__fechas__E9FBC1BFAA183CF9");

            entity.ToTable("fechas");

            entity.Property(e => e.IdFecha).HasColumnName("id_fecha");
            entity.Property(e => e.Fecha1)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
        });

        modelBuilder.Entity<FormasCompra>(entity =>
        {
            entity.HasKey(e => e.IdFcompra).HasName("PK__formas_c__99EEE88901CF3FCE");

            entity.ToTable("formas_compra");

            entity.Property(e => e.IdFcompra).HasColumnName("id_fcompra");
            entity.Property(e => e.FormaCompra)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("forma_compra");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.IdFpago).HasName("PK__formas_p__16905E25A4ECE6D0");

            entity.ToTable("formas_pago");

            entity.Property(e => e.IdFpago).HasColumnName("id_fpago");
            entity.Property(e => e.FormaPago)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("forma_pago");
        });

        modelBuilder.Entity<Formato>(entity =>
        {
            entity.HasKey(e => e.IdFormato).HasName("PK__formatos__8C0C34B7D741854D");

            entity.ToTable("formatos");

            entity.Property(e => e.IdFormato).HasColumnName("id_formato");
            entity.Property(e => e.Formato1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("formato");
        });

        modelBuilder.Entity<Funcione>(entity =>
        {
            entity.HasKey(e => e.CodFuncion).HasName("PK__funcione__723CE9A6D3B5C7D3");

            entity.ToTable("funciones");

            entity.Property(e => e.CodFuncion).HasColumnName("cod_funcion");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.IdButacaRes).HasColumnName("id_butaca_res");
            entity.Property(e => e.IdFecha).HasColumnName("id_fecha");
            entity.Property(e => e.IdHorario).HasColumnName("id_horario");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_funciones_pelicula");

            entity.HasOne(d => d.IdFechaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdFecha)
                .HasConstraintName("fk_funciones_fecha");

            entity.HasOne(d => d.IdHorarioNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdHorario)
                .HasConstraintName("fk_funciones_horario");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdSala)
                .HasConstraintName("fk_funciones_sala");
        });

        modelBuilder.Entity<GenerosPelicula>(entity =>
        {
            entity.HasKey(e => e.IdGenero).HasName("PK__generos___99A8E4F9107FC7CE");

            entity.ToTable("generos_peliculas");

            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.Genero)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("genero");
        });

        modelBuilder.Entity<Horario>(entity =>
        {
            entity.HasKey(e => e.IdHorario).HasName("PK__horarios__C5836D69A7A5BAB8");

            entity.ToTable("horarios");

            entity.Property(e => e.IdHorario).HasColumnName("id_horario");
            entity.Property(e => e.HoraFin).HasColumnName("hora_fin");
            entity.Property(e => e.HoraInicio).HasColumnName("hora_inicio");
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasKey(e => e.IdIdioma).HasName("PK__idiomas__0BA1525FF23B6AF0");

            entity.ToTable("idiomas");

            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.Idioma1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("idioma");
        });

        modelBuilder.Entity<Paise>(entity =>
        {
            entity.HasKey(e => e.IdPais).HasName("PK__paises__0941A3A7A93AFA2D");

            entity.ToTable("paises");

            entity.Property(e => e.IdPais).HasColumnName("id_pais");
            entity.Property(e => e.Pais)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("pais");
        });

        modelBuilder.Entity<Pelicula>(entity =>
        {
            entity.HasKey(e => e.CodPelicula).HasName("PK__pelicula__225F6E08D1FB0164");

            entity.ToTable("peliculas");

            entity.HasIndex(e => e.Titulo, "idx_peliculas_titulo");

            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.DuracionMin).HasColumnName("duracion_min");
            entity.Property(e => e.IdClasif).HasColumnName("id_clasif");
            entity.Property(e => e.IdFormato).HasColumnName("id_formato");
            entity.Property(e => e.IdPais).HasColumnName("id_pais");
            entity.Property(e => e.Titulo)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("titulo");

            entity.HasOne(d => d.IdClasifNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdClasif)
                .HasConstraintName("fk_peliculas_clasif");

            entity.HasOne(d => d.IdFormatoNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdFormato)
                .HasConstraintName("fk_peliculas_formato");

            entity.HasOne(d => d.IdPaisNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdPais)
                .HasConstraintName("fk_peliculas_pais");
        });

        modelBuilder.Entity<PreciosCombo>(entity =>
        {
            entity.HasKey(e => e.CodPrecioCombo).HasName("PK__precios___441FFDBF64B5059D");

            entity.ToTable("precios_combos");

            entity.Property(e => e.CodPrecioCombo).HasColumnName("cod_precio_combo");
            entity.Property(e => e.PrecioCombo)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_combo");
        });

        modelBuilder.Entity<PreciosProducto>(entity =>
        {
            entity.HasKey(e => e.CodPrecioProd).HasName("PK__precios___0844878028AE12EF");

            entity.ToTable("precios_productos");

            entity.Property(e => e.CodPrecioProd).HasColumnName("cod_precio_prod");
            entity.Property(e => e.CodProdKiosco).HasColumnName("cod_prod_kiosco");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");

            entity.HasOne(d => d.CodProdKioscoNavigation).WithMany(p => p.PreciosProductos)
                .HasForeignKey(d => d.CodProdKiosco)
                .HasConstraintName("fk_preciosprod_prod");
        });

        modelBuilder.Entity<PreciosSala>(entity =>
        {
            entity.HasKey(e => e.IdPreciosSala).HasName("PK__precios___4ACFCA1CD1F58ADB");

            entity.ToTable("precios_salas");

            entity.Property(e => e.IdPreciosSala).HasColumnName("id_precios_sala");
            entity.Property(e => e.PrecioSala)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_sala");
        });

        modelBuilder.Entity<ProductosKiosco>(entity =>
        {
            entity.HasKey(e => e.CodProdKiosco).HasName("PK__producto__77D49EE1EF757D4B");

            entity.ToTable("productos_kiosco");

            entity.Property(e => e.CodProdKiosco).HasColumnName("cod_prod_kiosco");
            entity.Property(e => e.Producto)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("producto");
        });

        modelBuilder.Entity<Promocione>(entity =>
        {
            entity.HasKey(e => e.IdPromo).HasName("PK__promocio__DFB74B64230290CE");

            entity.ToTable("promociones");

            entity.Property(e => e.IdPromo).HasColumnName("id_promo");
            entity.Property(e => e.Descuento)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("descuento");
            entity.Property(e => e.Promocion)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("promocion");
        });

        modelBuilder.Entity<PromosFecha>(entity =>
        {
            entity.HasKey(e => e.CodPromoFecha).HasName("PK__promos_f__7D7F38507C165339");

            entity.ToTable("promos_fechas");

            entity.Property(e => e.CodPromoFecha).HasColumnName("cod_promo_fecha");
            entity.Property(e => e.IdFecha).HasColumnName("id_fecha");
            entity.Property(e => e.IdPromo).HasColumnName("id_promo");

            entity.HasOne(d => d.IdFechaNavigation).WithMany(p => p.PromosFechas)
                .HasForeignKey(d => d.IdFecha)
                .HasConstraintName("fk_promosfechas_fecha");

            entity.HasOne(d => d.IdPromoNavigation).WithMany(p => p.PromosFechas)
                .HasForeignKey(d => d.IdPromo)
                .HasConstraintName("fk_promosfechas_promo");
        });

        modelBuilder.Entity<PromosHorario>(entity =>
        {
            entity.HasKey(e => e.CodPromoHorario).HasName("PK__promos_h__5BBFC79062AB624E");

            entity.ToTable("promos_horarios");

            entity.Property(e => e.CodPromoHorario).HasColumnName("cod_promo_horario");
            entity.Property(e => e.IdHorario).HasColumnName("id_horario");
            entity.Property(e => e.IdPromo).HasColumnName("id_promo");

            entity.HasOne(d => d.IdHorarioNavigation).WithMany(p => p.PromosHorarios)
                .HasForeignKey(d => d.IdHorario)
                .HasConstraintName("fk_promoshorarios_horario");

            entity.HasOne(d => d.IdPromoNavigation).WithMany(p => p.PromosHorarios)
                .HasForeignKey(d => d.IdPromo)
                .HasConstraintName("fk_promoshorarios_promo");
        });

        modelBuilder.Entity<Puesto>(entity =>
        {
            entity.HasKey(e => e.IdPuesto).HasName("PK__puestos__123AAB998DE7614C");

            entity.ToTable("puestos");

            entity.Property(e => e.IdPuesto).HasColumnName("id_puesto");
            entity.Property(e => e.Puesto1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("puesto");
        });

        modelBuilder.Entity<Reserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva).HasName("PK__reservas__423CBE5DD7CABC41");

            entity.ToTable("reservas");

            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.CodComprobante).HasColumnName("cod_comprobante");
            entity.Property(e => e.CodFuncion).HasColumnName("cod_funcion");
            entity.Property(e => e.FechaReserva)
                .HasColumnType("datetime")
                .HasColumnName("fecha_reserva");
            entity.Property(e => e.FechaVenc)
                .HasColumnType("datetime")
                .HasColumnName("fecha_venc");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdEstadoReserva).HasColumnName("id_estado_reserva");

            entity.HasOne(d => d.CodComprobanteNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.CodComprobante)
                .HasConstraintName("fk_reservas_comprobante");

            entity.HasOne(d => d.CodFuncionNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.CodFuncion)
                .HasConstraintName("fk_reservas_funcion");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("fk_reservas_cliente");

            entity.HasOne(d => d.IdEstadoReservaNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdEstadoReserva)
                .HasConstraintName("fk_reservas_estado");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("PK__roles__6ABCB5E029FA720A");

            entity.ToTable("roles");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.Rol)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("rol");
        });

        modelBuilder.Entity<Sala>(entity =>
        {
            entity.HasKey(e => e.IdSala).HasName("PK__salas__D18B015BA467A687");

            entity.ToTable("salas");

            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.IdDetSala).HasColumnName("id_det_sala");
            entity.Property(e => e.IdFecha).HasColumnName("id_fecha");
            entity.Property(e => e.IdHorario).HasColumnName("id_horario");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_salas_pelicula");

            entity.HasOne(d => d.IdDetSalaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdDetSala)
                .HasConstraintName("fk_salas_detalle_sala");

            entity.HasOne(d => d.IdFechaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdFecha)
                .HasConstraintName("fk_salas_fecha");

            entity.HasOne(d => d.IdHorarioNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdHorario)
                .HasConstraintName("fk_salas_horario");
        });

        modelBuilder.Entity<Sexo>(entity =>
        {
            entity.HasKey(e => e.IdSexo).HasName("PK__sexos__D692FEE6D25F99DB");

            entity.ToTable("sexos");

            entity.Property(e => e.IdSexo).HasColumnName("id_sexo");
            entity.Property(e => e.Sexo1)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("sexo");
        });

        modelBuilder.Entity<Subtitulo>(entity =>
        {
            entity.HasKey(e => e.IdSubtitulo).HasName("PK__subtitul__638D90B090DA1219");

            entity.ToTable("subtitulos");

            entity.Property(e => e.IdSubtitulo).HasColumnName("id_subtitulo");
            entity.Property(e => e.IdiomaSubt)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("idioma_subt");
        });

        modelBuilder.Entity<Ticket>(entity =>
        {
            entity.HasKey(e => e.CodTicket).HasName("PK__tickets__5BDA15439DC1DFB0");

            entity.ToTable("tickets");

            entity.Property(e => e.CodTicket).HasColumnName("cod_ticket");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.FechaFuncion)
                .HasColumnType("datetime")
                .HasColumnName("fecha_funcion");
            entity.Property(e => e.HorarioFuncion).HasColumnName("horario_funcion");
            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.IdTCliente).HasColumnName("id_t_cliente");
            entity.Property(e => e.NroButaca).HasColumnName("nro_butaca");

            entity.HasOne(d => d.CodPeliculaNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.CodPelicula)
                .HasConstraintName("fk_tickets_pelicula");

            entity.HasOne(d => d.IdFuncionNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.IdFuncion)
                .HasConstraintName("fk_tickets_funcion");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.IdSala)
                .HasConstraintName("fk_tickets_sala");

            entity.HasOne(d => d.IdTClienteNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.IdTCliente)
                .HasConstraintName("fk_tickets_tipo_cliente");
        });

        modelBuilder.Entity<TiposCliente>(entity =>
        {
            entity.HasKey(e => e.IdTCliente).HasName("PK__tipos_cl__A914970DFFB56FCF");

            entity.ToTable("tipos_clientes");

            entity.Property(e => e.IdTCliente).HasColumnName("id_t_cliente");
            entity.Property(e => e.IdDesCliente).HasColumnName("id_des_cliente");
            entity.Property(e => e.TCliente)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("t_cliente");

            entity.HasOne(d => d.IdDesClienteNavigation).WithMany(p => p.TiposClientes)
                .HasForeignKey(d => d.IdDesCliente)
                .HasConstraintName("fk_tiposclientes_desc");
        });

        modelBuilder.Entity<VistaRecaudacion>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vista_recaudacion");

            entity.Property(e => e.CantidadVentas).HasColumnName("Cantidad_Ventas");
            entity.Property(e => e.CodPelicula).HasColumnName("cod_pelicula");
            entity.Property(e => e.PromedioRecaudadoPorTicket).HasColumnName("Promedio_Recaudado_Por_Ticket");
            entity.Property(e => e.TicketsVendidos).HasColumnName("Tickets_Vendidos");
            entity.Property(e => e.TotalRecaudado)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("Total_Recaudado");
        });

        modelBuilder.Entity<VwGastoPorGeneroDuracion>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_GastoPorGeneroDuracion");

            entity.Property(e => e.Espectadores).HasColumnName("espectadores");
            entity.Property(e => e.Funciones).HasColumnName("funciones");
            entity.Property(e => e.GastoPromedio)
                .HasColumnType("decimal(38, 6)")
                .HasColumnName("gasto_promedio");
            entity.Property(e => e.GastoTotal)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("gasto_total");
            entity.Property(e => e.Genero)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("genero");
            entity.Property(e => e.RangoDuracion)
                .IsRequired()
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("rango_duracion");
        });

        modelBuilder.Entity<VwTopCombo>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TopCombos");

            entity.Property(e => e.CantidadVendida).HasColumnName("cantidad_vendida");
            entity.Property(e => e.Combo)
                .HasMaxLength(36)
                .IsUnicode(false)
                .HasColumnName("combo");
            entity.Property(e => e.GananciaTotal)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ganancia_total");
        });

        modelBuilder.Entity<VwTopProductosIndividuale>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_TopProductosIndividuales");

            entity.Property(e => e.CantidadVendida).HasColumnName("cantidad_vendida");
            entity.Property(e => e.GananciaTotal)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ganancia_total");
            entity.Property(e => e.Producto)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("producto");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}