// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TP_BD_P3.Models.Scaffolded;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial class TP_BD_P2Context
    {
        private ITP_BD_P2ContextProcedures _procedures;

        public virtual ITP_BD_P2ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TP_BD_P2ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITP_BD_P2ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TP_BD_P2ContextProcedures : ITP_BD_P2ContextProcedures
    {
        private readonly TP_BD_P2Context _context;

        public TP_BD_P2ContextProcedures(TP_BD_P2Context context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_ReporteConsumoKioscoResult>> sp_ReporteConsumoKioscoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_ReporteConsumoKioscoResult>("EXEC @returnValue = [dbo].[sp_ReporteConsumoKiosco]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_TopGeneroPorTipoClienteResult>> sp_TopGeneroPorTipoClienteAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_TopGeneroPorTipoClienteResult>("EXEC @returnValue = [dbo].[sp_TopGeneroPorTipoCliente]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_RecaudacionPorPeliculaResult>> usp_RecaudacionPorPeliculaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_RecaudacionPorPeliculaResult>("EXEC @returnValue = [dbo].[usp_RecaudacionPorPelicula]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_TopProductosKioscoPorGenero_AnioActualResult>> usp_TopProductosKioscoPorGenero_AnioActualAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_TopProductosKioscoPorGenero_AnioActualResult>("EXEC @returnValue = [dbo].[usp_TopProductosKioscoPorGenero_AnioActual]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
