// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial class usp_TopProductosKioscoPorGenero_AnioActualResult
    {
        [StringLength(255)]
        public string Género { get; set; }
        [StringLength(255)]
        public string Producto { get; set; }
        [Column("Cantidad Vendida (Producto)")]
        public int? CantidadVendidaProducto { get; set; }
        [Column("Monto Total Recaudado (Producto)", TypeName = "decimal(38,2)")]
        public decimal? MontoTotalRecaudadoProducto { get; set; }
        [Column("Promedio Gasto por Ticket del Género")]
        public double? PromedioGastoporTicketdelGénero { get; set; }
    }
}
