// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TP_BD_P3.Models.Scaffolded
{
    public partial class usp_RecaudacionPorPeliculaResult
    {
        public int cod_pelicula { get; set; }
        [StringLength(255)]
        public string Pelicula { get; set; }
        [StringLength(100)]
        public string Pais_Origen { get; set; }
        public int? Duracion_Minutos { get; set; }
        [Column("Total_Recaudado", TypeName = "decimal(38,2)")]
        public decimal? Total_Recaudado { get; set; }
        public int? Tickets_Vendidos { get; set; }
        public double? Promedio_Recaudado_Por_Ticket { get; set; }
        public int? Cantidad_Ventas { get; set; }
    }
}
