// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class VistaRecaudacion
{
    public int? CodPelicula { get; set; }

    public decimal? TotalRecaudado { get; set; }

    public int? TicketsVendidos { get; set; }

    public double? PromedioRecaudadoPorTicket { get; set; }

    public int? CantidadVentas { get; set; }
}