// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class VwGastoPorGeneroDuracion
{
    public string Genero { get; set; }

    public string RangoDuracion { get; set; }

    public int? Funciones { get; set; }

    public int? Espectadores { get; set; }

    public decimal? GastoTotal { get; set; }

    public decimal? GastoPromedio { get; set; }
}