// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TP_BD_P3.Models.Scaffolded;

public partial class VwTopCombo
{
    public string Combo { get; set; }

    public int? CantidadVendida { get; set; }

    public decimal? GananciaTotal { get; set; }
}